export const config = {
    MIN_SYMBOL_COUNT: 3,
    MAX_SYMBOL_COUNT: 10,
    STARTING_SYMBOL_COUNT: 4,
    MIN_SYMBOL_VARIANCE: 3,
    MAX_SYMBOL_VARIANCE: 26,
    STARTING_SYMBOL_VARIANCE: 4,
    STARTING_REPEATED_SYMBOLS: false,
};
