export const config = {
    MIN_SYMBOL_COUNT: 3,
    MAX_SYMBOL_COUNT: 8,
    STARTING_SYMBOL_COUNT: 4,
    MIN_SYMBOL_VARIANCE: 3,
    MAX_SYMBOL_VARIANCE: 9,
    STARTING_SYMBOL_VARIANCE: 4,
    STARTING_REPEATED_SYMBOLS: false,
    STARTING_WORDLE_MODE: false,
};
